import 'package:app/app/misc/sqlite.dart';
import 'package:app/model/local/practice.dart';

const List<String> inflowRoutes = [
  '인스타그램/페이스북',
  '유튜브',
  '지인 추천',
  '블로그/카페/커뮤니티',
  '기타',
];

// const Map<String, List<Practice>> practices = {
//   '하체 운동': [
//     Practice(
//       category: '하체 운동운동',
//       name: '스쿼트',
//     ),
//     Practice(
//       category: '하체 운동운동',
//       name: '레그 익스텐션',
//     ),
//   ],
//   '팔 운동': [
//     Practice(
//       category: '팔운동',
//       name: '덤벨컬',
//     ),
//     Practice(
//       category: '팔운동',
//       name: '바벨컬',
//     ),
//     Practice(
//       category: '팔운동',
//       name: '시티드 바벨컬',
//     ),
//     Practice(
//       category: '팔운동',
//       name: '아놀드컬',
//     ),
//     Practice(
//       category: '팔운동',
//       name: '해머컬',
//     ),
//   ],
//   '등 운동': [],
//   '가슴 운동': [],
//   '어깨 운동 운동': [],
//   '복근 운동': [],
//   '유산소 운동': [],
//   '전신 운동': [],
// };
const Map<String, List<Practice>> practices = {
  '전신 운동': [
    Practice(
      category: '전신 운동',
      name: '데드리프트',
      exerciseId: 1,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '헥스바 데드리프트',
      exerciseId: 2,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '파워 클린',
      exerciseId: 3,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '루마니안 데드리프트',
      exerciseId: 4,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '스모 데드리프트',
      exerciseId: 5,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '클린 앤 저크',
      exerciseId: 6,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '스내치',
      exerciseId: 7,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '클린',
      exerciseId: 8,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '클린 앤 프레스',
      exerciseId: 9,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '랙 풀',
      exerciseId: 10,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '행 클린',
      exerciseId: 11,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '스티프 레그 데드리프트',
      exerciseId: 12,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '파워 스내치',
      exerciseId: 13,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '쓰러스터',
      exerciseId: 14,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '푸쉬 저크',
      exerciseId: 15,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '데피시트 데드리프트',
      exerciseId: 16,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '싱글 레그 루마니안 데드리프트',
      exerciseId: 17,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '행 파워 클린',
      exerciseId: 18,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '스플릿 저크',
      exerciseId: 19,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '클린 하이 풀',
      exerciseId: 20,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '스내치 데드리프트',
      exerciseId: 21,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '클린 풀',
      exerciseId: 22,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '포즈 데드리프트',
      exerciseId: 23,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '싱글 레그 데드리프트',
      exerciseId: 24,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '머슬 스내치',
      exerciseId: 25,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '제퍼슨 데드리프트',
      exerciseId: 26,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '스내치 풀',
      exerciseId: 27,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '월 볼',
      exerciseId: 28,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '저쳐 데드리프트',
      exerciseId: 29,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '행 스내치',
      exerciseId: 30,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '비하인드 백 데드리프트',
      exerciseId: 31,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '머슬 업',
      exerciseId: 32,
      thresholdType: 0,
    ),
    Practice(
      category: '전신 운동',
      name: '버피',
      exerciseId: 33,
      thresholdType: 0,
    ),
    Practice(
      category: '전신 운동',
      name: '링 머슬 업',
      exerciseId: 34,
      thresholdType: 0,
    ),
    Practice(
      category: '전신 운동',
      name: '클랩 풀업',
      exerciseId: 35,
      thresholdType: 0,
    ),
    Practice(
      category: '전신 운동',
      name: '스쿼트 쓰러스트',
      exerciseId: 36,
      thresholdType: 0,
    ),
    Practice(
      category: '전신 운동',
      name: '덤벨 루마니안 데드리프트',
      exerciseId: 37,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '덤벨 데드리프트',
      exerciseId: 38,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '덤벨 스내치',
      exerciseId: 39,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '싱글 레그 덤벨 데드리프트',
      exerciseId: 40,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '덤벨 클린 앤 프레스',
      exerciseId: 41,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '덤벨 쓰러스터',
      exerciseId: 42,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '덤벨 하이 풀',
      exerciseId: 43,
      thresholdType: 1,
    ),
    Practice(
      category: '전신 운동',
      name: '덤벨 행 클린',
      exerciseId: 44,
      thresholdType: 1,
    ),
  ],
  '하체 운동': [
    Practice(
      category: '하체 운동',
      name: '바디웨이트 스쿼트',
      exerciseId: 45,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '싱글 레그 스쿼트',
      exerciseId: 46,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '피스톨 스쿼트',
      exerciseId: 47,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '바디웨이트 카프 레이즈',
      exerciseId: 48,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '런지',
      exerciseId: 49,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '글루트 브릿지',
      exerciseId: 50,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '리버스 런지',
      exerciseId: 51,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '스쿼트 점프',
      exerciseId: 52,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '노르딕 햄스트링 컬',
      exerciseId: 53,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '시시 스쿼트',
      exerciseId: 54,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '글루트 햄 레이즈',
      exerciseId: 55,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '사이드 런지',
      exerciseId: 56,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '글루트 킥백',
      exerciseId: 57,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '돈키 카프 레이즈',
      exerciseId: 58,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '사이드 레그 레이즈',
      exerciseId: 59,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '플로우 힙 어브덕션',
      exerciseId: 60,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '힙 익스텐션',
      exerciseId: 61,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '플로우 힙 익스텐션 ',
      exerciseId: 62,
      thresholdType: 0,
    ),
    Practice(
      category: '하체 운동',
      name: '덤벨 불가리안 스플릿 스쿼트',
      exerciseId: 63,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '고블렛 스쿼트',
      exerciseId: 64,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '덤벨 런지',
      exerciseId: 65,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '덤벨 스쿼트',
      exerciseId: 66,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '덤벨 카프 레이즈',
      exerciseId: 67,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '덤벨 프론트 스쿼트',
      exerciseId: 68,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '덤벨 스플릿 스쿼트',
      exerciseId: 69,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '덤벨 워킹 카프 레이즈',
      exerciseId: 70,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '슬레드 레그 프레스',
      exerciseId: 71,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '레그 익스텐션',
      exerciseId: 72,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '수평 레그 프레스',
      exerciseId: 73,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '핵 스쿼트',
      exerciseId: 74,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '시티드 레그 컬',
      exerciseId: 75,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '라잉 레그 컬',
      exerciseId: 76,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '머신 카프 레이즈',
      exerciseId: 77,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '수직 레그 프레스',
      exerciseId: 78,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '시티드 카프 레이즈',
      exerciseId: 79,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '힙 어브덕션',
      exerciseId: 80,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '힙 어덕션',
      exerciseId: 81,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '스탠딩 레그 컬',
      exerciseId: 82,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '싱글 레그 프레스',
      exerciseId: 83,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '슬레드 프레스 카프 레이즈',
      exerciseId: 84,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '벨트 스쿼트',
      exerciseId: 85,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '싱글 레그 시티드 카프 레이즈',
      exerciseId: 86,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '케이블 풀 스루',
      exerciseId: 87,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '케이블 킥백',
      exerciseId: 88,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '케이블 레그 익스텐션',
      exerciseId: 89,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '스쿼트',
      exerciseId: 251,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '프론트 스쿼트',
      exerciseId: 252,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '힙 쓰러스트',
      exerciseId: 253,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '박스 스쿼트',
      exerciseId: 254,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '불가리안 스플릿 스쿼트',
      exerciseId: 255,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '스미스 머신 스쿼트',
      exerciseId: 256,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '저쳐 스쿼트',
      exerciseId: 257,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '굿모닝',
      exerciseId: 258,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '바벨 런지',
      exerciseId: 259,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '오버헤드 스쿼트',
      exerciseId: 260,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '바벨 카프 레이즈',
      exerciseId: 261,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '스플릿 스쿼트',
      exerciseId: 262,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '바벨 리버스 런지',
      exerciseId: 263,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '바벨 글루트 브릿지',
      exerciseId: 264,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '랜드마인 스쿼트',
      exerciseId: 265,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '세이프티 바 스쿼트',
      exerciseId: 266,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '포즈 스쿼트',
      exerciseId: 267,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '바벨 핵 스쿼트',
      exerciseId: 268,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '스모 스쿼트',
      exerciseId: 269,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '핀 스쿼트',
      exerciseId: 270,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '워킹 런지',
      exerciseId: 271,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '하프 스쿼트',
      exerciseId: 272,
      thresholdType: 1,
    ),
    Practice(
      category: '하체 운동',
      name: '제퍼슨 스쿼트',
      exerciseId: 273,
      thresholdType: 1,
    ),
  ],
  '등 운동': [
    Practice(
      category: '등 운동',
      name: '풀업',
      exerciseId: 90,
      thresholdType: 0,
    ),
    Practice(
      category: '등 운동',
      name: '친업',
      exerciseId: 91,
      thresholdType: 0,
    ),
    Practice(
      category: '등 운동',
      name: '뉴트럴 그립 풀업',
      exerciseId: 92,
      thresholdType: 0,
    ),
    Practice(
      category: '등 운동',
      name: '백 익스텐션',
      exerciseId: 93,
      thresholdType: 0,
    ),
    Practice(
      category: '등 운동',
      name: '원 암 풀업',
      exerciseId: 94,
      thresholdType: 0,
    ),
    Practice(
      category: '등 운동',
      name: '인버티드 로우',
      exerciseId: 95,
      thresholdType: 0,
    ),
    Practice(
      category: '등 운동',
      name: '리버스 하이퍼익스텐션',
      exerciseId: 96,
      thresholdType: 0,
    ),
    Practice(
      category: '등 운동',
      name: '덤벨 로우',
      exerciseId: 97,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '덤벨 슈러그',
      exerciseId: 98,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '덤벨 풀오버',
      exerciseId: 99,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '덤벨 리버스 플라이',
      exerciseId: 100,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '체스트 서포트 덤벨 로우',
      exerciseId: 101,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '벤트 오버 덤벨 로우',
      exerciseId: 102,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '레니게이드 로우',
      exerciseId: 103,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '덤벨 벤치 풀',
      exerciseId: 104,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '덤벨 인클라인 Y 레이즈',
      exerciseId: 105,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '머신 로우',
      exerciseId: 106,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '머신 리버스 플라이',
      exerciseId: 107,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '머신 백 익스텐션',
      exerciseId: 108,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '머신 슈러그',
      exerciseId: 109,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '랫 풀다운',
      exerciseId: 110,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '시티드 케이블 로우',
      exerciseId: 111,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '클로즈 그립 랫 풀다운',
      exerciseId: 112,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '리버스 그립 랫 풀다운',
      exerciseId: 113,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '스트레이트 암 풀다운',
      exerciseId: 114,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '케이블 리버스 플라이',
      exerciseId: 115,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '원 암 랫 풀다운',
      exerciseId: 116,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '원 암 시티드 케이블 로우',
      exerciseId: 117,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '케이블 업라이트 로우',
      exerciseId: 118,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '케이블 슈러그',
      exerciseId: 119,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '벤트 오버 로우',
      exerciseId: 274,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '바벨 슈러그',
      exerciseId: 275,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: 'T 바 로우',
      exerciseId: 276,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '펜들레이 로우',
      exerciseId: 277,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '예이츠 로우',
      exerciseId: 278,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '벤치 풀',
      exerciseId: 279,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '바벨 풀오버',
      exerciseId: 280,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '헥스 바 슈러그',
      exerciseId: 281,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '스미스 머신 슈러그',
      exerciseId: 282,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '바벨 파워 슈러그',
      exerciseId: 283,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '벤트 암 바벨 풀오버',
      exerciseId: 284,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '메도우즈 로우',
      exerciseId: 285,
      thresholdType: 1,
    ),
    Practice(
      category: '등 운동',
      name: '비하인드 백 바벨 슈러그',
      exerciseId: 286,
      thresholdType: 1,
    ),
  ],
  '가슴 운동': [
    Practice(
      category: '가슴 운동',
      name: '벤치 프레스',
      exerciseId: 120,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '인클라인 벤치 프레스',
      exerciseId: 121,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '클로즈 그립 벤치 프레스',
      exerciseId: 122,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '디클라인 벤치 프레스',
      exerciseId: 123,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '스미스 머신 벤치 프레스',
      exerciseId: 124,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '플로어 프레스',
      exerciseId: 125,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '포즈 벤치 프레스',
      exerciseId: 126,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '리버스 그립 벤치 프레스',
      exerciseId: 127,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '벤치 핀 프레스',
      exerciseId: 128,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '와이드 그립 벤치 프레스',
      exerciseId: 129,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '클로즈 그립 인클라인 벤치 프레스',
      exerciseId: 130,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '스포토 프레스',
      exerciseId: 131,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '푸쉬업',
      exerciseId: 132,
      thresholdType: 0,
    ),
    Practice(
      category: '가슴 운동',
      name: '원 암 푸쉬업',
      exerciseId: 133,
      thresholdType: 0,
    ),
    Practice(
      category: '가슴 운동',
      name: '다이아몬드 푸쉬업',
      exerciseId: 134,
      thresholdType: 0,
    ),
    Practice(
      category: '가슴 운동',
      name: '디클라인 푸쉬업',
      exerciseId: 135,
      thresholdType: 0,
    ),
    Practice(
      category: '가슴 운동',
      name: '인클라인 푸쉬업',
      exerciseId: 136,
      thresholdType: 0,
    ),
    Practice(
      category: '가슴 운동',
      name: '클로즈 그립 푸쉬업',
      exerciseId: 137,
      thresholdType: 0,
    ),
    Practice(
      category: '가슴 운동',
      name: '아처 푸쉬업',
      exerciseId: 138,
      thresholdType: 0,
    ),
    Practice(
      category: '가슴 운동',
      name: '덤벨 벤치 프레스',
      exerciseId: 139,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '인클라인 덤벨 벤치 프레스',
      exerciseId: 140,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '덤벨 플라이',
      exerciseId: 141,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '인클라인 덤벨 플라이',
      exerciseId: 142,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '덤벨 플로어 프레스',
      exerciseId: 143,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '디클라인 덤벨 벤치 프레스',
      exerciseId: 144,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '클로즈 그립 덤벨 벤치 프레스',
      exerciseId: 145,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '디클라인 덤벨 플라이',
      exerciseId: 146,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '체스트 프레스',
      exerciseId: 147,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '머신 체스트 플라이',
      exerciseId: 148,
      thresholdType: 1,
    ),
    Practice(
      category: '가슴 운동',
      name: '케이블 플라이',
      exerciseId: 149,
      thresholdType: 1,
    ),
  ],
  '어깨 운동': [
    Practice(
      category: '어깨 운동',
      name: '오버헤드 프레스',
      exerciseId: 150,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '밀리터리 프레스',
      exerciseId: 151,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '시티드 숄더 프레스',
      exerciseId: 152,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '푸쉬 프레스',
      exerciseId: 153,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '업라이트 로우',
      exerciseId: 154,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '넥 컬',
      exerciseId: 155,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '비하인드 넥 프레스',
      exerciseId: 156,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '바벨 프론트 레이즈',
      exerciseId: 157,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '로그 프레스',
      exerciseId: 158,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '랜드마인 프레스',
      exerciseId: 159,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '넥 익스텐션',
      exerciseId: 160,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: 'Z 프레스',
      exerciseId: 161,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '바이킹 프레스',
      exerciseId: 162,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '숄더 핀 프레스',
      exerciseId: 163,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '원 암 랜드마인 프레스',
      exerciseId: 164,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '핸드스탠드 푸쉬업',
      exerciseId: 165,
      thresholdType: 0,
    ),
    Practice(
      category: '어깨 운동',
      name: '파이크 푸쉬업',
      exerciseId: 166,
      thresholdType: 0,
    ),
    Practice(
      category: '어깨 운동',
      name: '덤벨 숄더 프레스',
      exerciseId: 167,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '덤벨 레터럴 레이즈',
      exerciseId: 168,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '시티드 덤벨 숄더 프레스',
      exerciseId: 169,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '덤벨 프론트 레이즈',
      exerciseId: 170,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '아놀드 프레스',
      exerciseId: 171,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '덤벨 업라이트 로우',
      exerciseId: 172,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '덤벨 Z 프레스',
      exerciseId: 173,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '덤벨 외회전',
      exerciseId: 174,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '덤벨 푸쉬 프레스',
      exerciseId: 175,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '덤벨 페이스 풀',
      exerciseId: 176,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '머신 숄더 프레스',
      exerciseId: 177,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '머신 레터럴 레이즈',
      exerciseId: 178,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '케이블 레터럴 레이즈',
      exerciseId: 179,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '페이스 풀',
      exerciseId: 180,
      thresholdType: 1,
    ),
    Practice(
      category: '어깨 운동',
      name: '케이블 익스터널 로테이션',
      exerciseId: 181,
      thresholdType: 1,
    ),
  ],
  '이두 운동': [
    Practice(
      category: '이두 운동',
      name: '바벨 컬',
      exerciseId: 182,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '이지바 컬',
      exerciseId: 183,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '프리처 컬',
      exerciseId: 184,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '스트릭트 컬',
      exerciseId: 185,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '스파이더 컬',
      exerciseId: 186,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '치트 컬',
      exerciseId: 187,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '덤벨 컬',
      exerciseId: 188,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '해머 컬',
      exerciseId: 189,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '인클라인 덤벨 컬',
      exerciseId: 190,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '덤벨 컨센트레이션 컬',
      exerciseId: 191,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '원 암 덤벨 프리처 컬',
      exerciseId: 192,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '인클라인 해머 컬',
      exerciseId: 193,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '시티드 덤벨 컬',
      exerciseId: 194,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '조트만 컬',
      exerciseId: 195,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '머신 바이셉스 컬',
      exerciseId: 196,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '케이블 바이셉스 컬',
      exerciseId: 197,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '원 암 케이블 바이셉스 컬',
      exerciseId: 198,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '케이블 해머 컬',
      exerciseId: 199,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '원 암 풀다운',
      exerciseId: 200,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '오버헤드 케이블 컬',
      exerciseId: 201,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '인클라인 케이블 컬',
      exerciseId: 202,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '라잉 케이블 컬',
      exerciseId: 203,
      thresholdType: 1,
    ),
    Practice(
      category: '이두 운동',
      name: '덤벨 리버스 컬',
      exerciseId: 287,
      thresholdType: 1,
    ),
  ],
  '삼두 운동': [
    Practice(
      category: '삼두 운동',
      name: '라잉 트라이셉스 익스텐션',
      exerciseId: 204,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '트라이셉스 익스텐션',
      exerciseId: 205,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: 'JM 프레스',
      exerciseId: 206,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '딥스',
      exerciseId: 207,
      thresholdType: 0,
    ),
    Practice(
      category: '삼두 운동',
      name: '링 딥스',
      exerciseId: 208,
      thresholdType: 0,
    ),
    Practice(
      category: '삼두 운동',
      name: '벤치 딥스',
      exerciseId: 209,
      thresholdType: 0,
    ),
    Practice(
      category: '삼두 운동',
      name: '덤벨 트라이셉스 익스텐션',
      exerciseId: 210,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '라잉 덤벨 트라이셉스 익스텐션',
      exerciseId: 211,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '덤벨 트라이셉스 킥백',
      exerciseId: 212,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '시티드 덤벨 트라이셉스 익스텐션',
      exerciseId: 213,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '테이트 프레스',
      exerciseId: 214,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '시티드 딥 머신',
      exerciseId: 215,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '머신 트라이셉스 익스텐션',
      exerciseId: 216,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '트라이셉스 푸쉬다운',
      exerciseId: 217,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '트라이셉스 로프 푸쉬다운',
      exerciseId: 218,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '케이블 오버헤드 트라이셉스 익스텐션',
      exerciseId: 219,
      thresholdType: 1,
    ),
    Practice(
      category: '삼두 운동',
      name: '리버스 그립 트라이셉스 푸쉬다운',
      exerciseId: 220,
      thresholdType: 1,
    ),
  ],
  '코어 운동': [
    Practice(
      category: '코어 운동',
      name: '싯업',
      exerciseId: 221,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '크런치',
      exerciseId: 222,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '행잉 레그 레이즈',
      exerciseId: 223,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '러시안 트위스트',
      exerciseId: 224,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '라잉 레그 레이즈',
      exerciseId: 225,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '디클라인 싯업',
      exerciseId: 226,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '행잉 니 레이즈',
      exerciseId: 227,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '복부 휠 롤아웃',
      exerciseId: 228,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '토 투 바',
      exerciseId: 229,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '디클라인 크런치',
      exerciseId: 230,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '점핑 잭',
      exerciseId: 231,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '바이시클 크런치',
      exerciseId: 232,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '리버스 크런치',
      exerciseId: 233,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '마운틴 클라이머',
      exerciseId: 234,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '플러터 킥',
      exerciseId: 235,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '슈퍼맨',
      exerciseId: 236,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '사이드 크런치',
      exerciseId: 237,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '로만 체어 사이드 밴드',
      exerciseId: 238,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '시저 킥',
      exerciseId: 239,
      thresholdType: 0,
    ),
    Practice(
      category: '코어 운동',
      name: '덤벨 사이드 밴드',
      exerciseId: 240,
      thresholdType: 1,
    ),
    Practice(
      category: '코어 운동',
      name: '머신 시티드 크런치',
      exerciseId: 241,
      thresholdType: 1,
    ),
    Practice(
      category: '코어 운동',
      name: '케이블 크런치',
      exerciseId: 242,
      thresholdType: 1,
    ),
    Practice(
      category: '코어 운동',
      name: '케이블 우드초퍼',
      exerciseId: 243,
      thresholdType: 1,
    ),
    Practice(
      category: '코어 운동',
      name: '하이 풀리 크런치',
      exerciseId: 244,
      thresholdType: 1,
    ),
    Practice(
      category: '코어 운동',
      name: '스탠딩 케이블 크런치',
      exerciseId: 245,
      thresholdType: 1,
    ),
  ],
  '전완근 운동': [
    Practice(
      category: '전완근 운동',
      name: '리스트 컬',
      exerciseId: 246,
      thresholdType: 1,
    ),
    Practice(
      category: '전완근 운동',
      name: '리버스 바벨 컬',
      exerciseId: 247,
      thresholdType: 1,
    ),
    Practice(
      category: '전완근 운동',
      name: '리버스 리스트 컬',
      exerciseId: 248,
      thresholdType: 1,
    ),
    Practice(
      category: '전완근 운동',
      name: '덤벨 리스트 컬',
      exerciseId: 249,
      thresholdType: 1,
    ),
    Practice(
      category: '전완근 운동',
      name: '덤벨 리버스 리스트 컬',
      exerciseId: 250,
      thresholdType: 1,
    ),
  ],
};
